plugins {
    id 'application'
    id 'java'
}

version = "${majorVersion}.${minorVersion}.${patchVersion}"
group = project.group

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.sqlite.jdbc

    implementation libs.guava
    implementation libs.logback.classic 

    implementation libs.javalin.bundle
    implementation libs.javalin.rendering

    implementation libs.thymeleaf

    implementation libs.jbcrypt
    implementation libs.jjwt.api
    runtimeOnly libs.jjwt.impl
    runtimeOnly libs.jjwt.jackson

    implementation libs.dotenv.java

    implementation libs.owasp.java.html.sanitizer
    
    implementation libs.pdfbox
    implementation libs.zxing.core
    implementation libs.zxing.javase
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'dev.vertesix.credifyqr.bootstrap.App'
    applicationDefaultJvmArgs = ["-Dlogback.configurationFile=src/main/resources/logback-main.xml"]
}

run {
    systemProperty "logback.configurationFile", "src/main/resources/logback-main.xml"
}

jar {
    manifest {
        attributes 'Main-Class': 'dev.vertesix.credifyqr.bootstrap.App' 
    }
    archiveFileName = "${project.name}-${project.version}.jar"
    destinationDirectory = file("$rootDir")
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

javadoc {
    source = sourceSets.main.allJava
    classpath = configurations.compileClasspath
    destinationDir = file("${buildDir}/docs/javadoc")
    options.addStringOption('Xdoclint:none', '-quiet')
    
    options {
        encoding = 'UTF-8'
        charSet = 'UTF-8'
        author = true
        version = true
    }
}

build.dependsOn javadoc
