package dev.vertesix.credifyqr.Identity.core.domain;

/**
 * Categorizes audit events generated by identity and document operations.
 */
public enum ActionType {
    /** Successful authentication event. */
    LOGIN_SUCCESS,
    /** Failed authentication attempt. */
    LOGIN_FAILED,
    /** User successfully claimed an account. */
    ACCOUNT_CLAIMED,
    /** A role or permission was modified. */
    ROLE_MODIFIED,
    /** A password was changed. */
    PASSWORD_CHANGED,
    /** A new user was provisioned. */
    USER_PROVISIONED,
    /** The institution domain was updated. */
    DOMAIN_UPDATED,
    /** Cache clearing or invalidation occurred. */
    CACHE_CLEARED
}