package dev.vertesix.credifyqr.Identity.core.ports;

import dev.vertesix.credifyqr.Identity.core.domain.AuditLog;

/**
 * Port for persisting audit log events generated by identity and document operations.
 *
 * <p>Implementations of this interface store immutable audit records for
 * security and compliance tracking.</p>
 */
public interface AuditRepository {
    /**
     * Saves a single audit log entry.
     *
     * @param log the audit log record to persist
     */
    void save(AuditLog log);
}